import abc
from _typeshed import Incomplete
from abc import ABC, abstractmethod
from client_utils import AccountClient
from com.exteragram.messenger.plugins.hooks import HookFilter as JavaHookFilter
from dataclasses import dataclass
from de.robv.android.xposed import XC_MethodHook as XC_MethodHook
from enum import Enum
from file_utils import FilesController
from intents import IntentsManager
from java.lang import Class as Class
from java.lang.reflect import Member as Member
from typing import Any, Callable, final

@dataclass
class PluginMetadata:
    id: str
    name: str
    description: str
    author: str
    version: str
    icon: str
    min_version: str
    requirements: list[str]

class HookStrategy(Enum):
    CANCEL = ...
    MODIFY = ...
    DEFAULT = ...
    MODIFY_FINAL = ...

class IntentHookType(Enum):
    BEFORE = 0
    AFTER = 1

@dataclass
class HookResult:
    strategy: HookStrategy = ...
    request: Any = ...
    response: Any = ...
    update: Any = ...
    updates: Any = ...
    error: Any = ...
    params: Any = ...

class PluginError(Exception):
    plugin_id: str | None
    def __init__(self, message: str, plugin_id: str | None = None) -> None: ...

class XposedHook(ABC): ...

class MethodReplacement(XposedHook, metaclass=abc.ABCMeta):
    @abstractmethod
    def replace_hooked_method(self, param: XC_MethodHook.MethodHookParam) -> Any: ...

class MethodHook(XposedHook):
    def before_hooked_method(self, param: XC_MethodHook.MethodHookParam): ...
    def after_hooked_method(self, param: XC_MethodHook.MethodHookParam): ...

def fn_hook_filters(field_name: str): ...

class BaseHook(MethodHook):
    plugin: Incomplete
    before: Incomplete
    after: Incomplete
    before_filters: Incomplete
    after_filters: Incomplete
    def __init__(self, plugin: BasePlugin | None = None, *, before: Callable | None = None, after: Callable | None = None, before_filters: list[Any] | None = None, after_filters: list[Any] | None = None) -> None: ...
    def before_hooked_method(self, param) -> None: ...
    def after_hooked_method(self, param) -> None: ...

class AppEvent(Enum):
    START = ...
    STOP = ...
    PAUSE = ...
    RESUME = ...

class MenuItemType(Enum):
    MESSAGE_CONTEXT_MENU = ...
    DRAWER_MENU = ...
    MAIN_MENU = ...
    CHAT_ACTION_MENU = ...
    PROFILE_ACTION_MENU = ...

@dataclass
class MenuItemData:
    menu_type: MenuItemType
    text: str
    on_click: Callable[[dict[str, Any]], None]
    item_id: str | None = ...
    icon: str | None = ...
    subtext: str | None = ...
    condition: str | None = ...
    priority: int = ...

@dataclass
class HookFilterData:
    filter_type: str
    arg_index: int | None = ...
    or_filters: Any | None = ...
    mvel_expression: str | None = ...
    instance_of: Any | None = ...
    object: Any = ...
    def to_java_filter(self) -> JavaHookFilter: ...

class HookFilter(Enum):
    RESULT_IS_NULL = ...
    RESULT_IS_TRUE = ...
    RESULT_IS_FALSE = ...
    RESULT_NOT_NULL = ...
    @property
    def filter_data(self): ...
    @staticmethod
    def ResultIsInstanceOf(clazz): ...
    @staticmethod
    def ResultEqual(value): ...
    @staticmethod
    def ResultNotEqual(value): ...
    @staticmethod
    def ArgumentIsNull(index: int): ...
    @staticmethod
    def ArgumentIsTrue(index: int): ...
    @staticmethod
    def ArgumentIsFalse(index: int): ...
    @staticmethod
    def ArgumentNotNull(index: int): ...
    @staticmethod
    def ArgumentIsInstanceOf(index: int, clazz): ...
    @staticmethod
    def ArgumentEqual(index: int, value): ...
    @staticmethod
    def ArgumentNotEqual(index: int, value): ...
    @staticmethod
    def Condition(condition: str, object: Any = None): ...
    @staticmethod
    def Or(*filters): ...

def hook_filters(*filters): ...

class BasePlugin:
    def __new__(cls): ...
    def __init_subclass__(cls, **kwargs) -> None: ...
    id: str
    name: str
    description: str
    author: str
    min_version: str
    version: str
    requirements: list[str]
    icon: str | None
    error_message: str | None
    enabled: bool
    initialized: bool
    def __init__(self) -> None: ...
    def on_plugin_load(self) -> None: ...
    def on_plugin_unload(self) -> None: ...
    def create_settings(self) -> list[Any]: ...
    def on_app_event(self, event_type: AppEvent): ...
    def pre_request_hook(self, request_name: str, account: int, request: Any) -> HookResult: ...
    def post_request_hook(self, request_name: str, account: int, response: Any, error: Any) -> HookResult: ...
    def on_update_hook(self, update_name: str, account: int, update: Any) -> HookResult: ...
    def on_updates_hook(self, container_name: str, account: int, updates: Any) -> HookResult: ...
    def on_send_message_hook(self, account: int, params: Any) -> HookResult: ...
    @final
    def add_hook(self, name: str, match_substring: bool = False, priority: int = 0): ...
    @final
    def add_on_send_message_hook(self, priority: int = 0): ...
    @final
    def remove_hook(self, name: str): ...
    @final
    def add_file_hook(self, file_info: FilesController.FileInfo): ...
    @final
    def remove_file_hook(self, ext, secret) -> None: ...
    @final
    def add_intent_hook(self, info: IntentsManager.HandlerInfo, type: IntentHookType): ...
    @final
    def remove_intent_hook(self, handler_id: IntentsManager.HandlerHandle | str): ...
    @final
    def get_setting(self, key: str, default: Any = None) -> Any: ...
    @final
    def set_setting(self, key: str, value: Any, reload_settings: bool = False): ...
    @final
    def export_settings(self) -> dict: ...
    @final
    def import_settings(self, settings: dict, reload_settings: bool = True): ...
    @final
    def hook_method(self, method_or_constructor: Member, xposed_hook: Any | None = None, priority: int | None = None, *, before: Callable | None = None, after: Callable | None = None, before_filters: list[Any] | None = None, after_filters: list[Any] | None = None) -> XC_MethodHook.Unhook | None: ...
    @final
    def hook_all_methods(self, hook_class: Class, method_name: str, xposed_hook: Any | None = None, priority: int | None = None, *, before: Callable | None = None, after: Callable | None = None, before_filters: list[Any] | None = None, after_filters: list[Any] | None = None) -> list[XC_MethodHook.Unhook] | None: ...
    @final
    def hook_all_constructors(self, hook_class: Class, xposed_hook: Any | None = None, priority: int | None = None, *, before: Callable | None = None, after: Callable | None = None, before_filters: list[Any] | None = None, after_filters: list[Any] | None = None) -> list[XC_MethodHook.Unhook] | None: ...
    @final
    def unhook_method(self, unhook: XC_MethodHook.Unhook): ...
    @final
    def log(self, message: str): ...
    @final
    def client(self, account: int | None = None) -> AccountClient: ...
    @final
    def add_menu_item(self, menu_item_data: MenuItemData) -> str | None: ...
    @final
    def remove_menu_item(self, item_id: str) -> bool: ...
