import contextlib
from _typeshed import Incomplete
from java.lang import Object as Object
from org.telegram.messenger import DispatchQueue
from org.telegram.tgnet import TLObject as TLObject, TLRPC
from typing import Any

STAGE_QUEUE: str
GLOBAL_QUEUE: str
CACHE_CLEAR_QUEUE: str
SEARCH_QUEUE: str
PHONE_BOOK_QUEUE: str
THEME_QUEUE: str
EXTERNAL_NETWORK_QUEUE: str
PLUGINS_QUEUE: str

def get_selected_account() -> int: ...
def get_hook_account() -> int | None: ...
@contextlib.contextmanager
def account_scope(account: int | None): ...
def get_queue_by_name(queue_name: str) -> DispatchQueue | None: ...
def run_on_queue(fn: callable, queue_name: str = ..., delay: int = 0): ...

class RequestCallback(Incomplete):
    def __init__(self, fn: callable, account: int | None = None) -> None: ...
    def run(self, response: TLObject, error: TLRPC.TL_error): ...

def send_request(request: Any, fn: callable, *, account: int | None = None) -> int: ...
def get_last_fragment(): ...
def get_account_instance(account: int | None = None): ...
def get_messages_controller(account: int | None = None): ...
def get_contacts_controller(account: int | None = None): ...
def get_media_data_controller(account: int | None = None): ...
def get_connections_manager(account: int | None = None): ...
def get_location_controller(account: int | None = None): ...
def get_notifications_controller(account: int | None = None): ...
def get_messages_storage(account: int | None = None): ...
def get_send_messages_helper(account: int | None = None): ...
def get_file_loader(account: int | None = None): ...
def get_secret_chat_helper(account: int | None = None): ...
def get_download_controller(account: int | None = None): ...
def get_notifications_settings(account: int | None = None): ...
def get_notification_center(account: int | None = None): ...
def get_media_controller(): ...
def get_user_config(account: int | None = None): ...
def send_message(params: dict, parse_mode: str = None, *, account: int | None = None): ...
def send_text(peer: int, text: str, *, account: int | None = None, parse_mode: str | None = None, **kwargs): ...
def send_photo(peer: int, file_path: str, caption: str = '', high_quality: bool = False, *, account: int | None = None, parse_mode: str | None = None, **kwargs): ...
def send_document(peer: int, file_path: str, caption: str = '', *, account: int | None = None, parse_mode: str | None = None, **kwargs): ...
def send_video(peer: int, file_path: str, caption: str = '', *, account: int | None = None, parse_mode: str | None = None, **kwargs): ...
def send_audio(peer: int, file_path: str, caption: str = '', *, account: int | None = None, parse_mode: str | None = None, **kwargs): ...
def edit_message(message_obj: Any, text: str | None = None, file_path: str | None = None, with_spoiler: bool = False, *, account: int | None = None, parse_mode: str | None = None, **kwargs): ...

class AccountClient:
    account: Incomplete
    def __init__(self, account: int) -> None: ...
    def __eq__(self, other): ...
    def __hash__(self): ...
    def get_account_instance(self): ...
    def get_messages_controller(self): ...
    def get_contacts_controller(self): ...
    def get_media_data_controller(self): ...
    def get_connections_manager(self): ...
    def get_location_controller(self): ...
    def get_notifications_controller(self): ...
    def get_messages_storage(self): ...
    def get_send_messages_helper(self): ...
    def get_file_loader(self): ...
    def get_secret_chat_helper(self): ...
    def get_download_controller(self): ...
    def get_notifications_settings(self): ...
    def get_notification_center(self): ...
    def get_user_config(self): ...
    def send_request(self, request: Any, fn: callable) -> int: ...
    def send_message(self, params: dict, parse_mode: str = None): ...
    def send_text(self, peer: int, text: str, *, parse_mode: str | None = None, **kwargs): ...
    def send_photo(self, peer: int, file_path: str, caption: str = '', high_quality: bool = False, *, parse_mode: str | None = None, **kwargs): ...
    def send_document(self, peer: int, file_path: str, caption: str = '', *, parse_mode: str | None = None, **kwargs): ...
    def send_video(self, peer: int, file_path: str, caption: str = '', *, parse_mode: str | None = None, **kwargs): ...
    def send_audio(self, peer: int, file_path: str, caption: str = '', *, parse_mode: str | None = None, **kwargs): ...
    def edit_message(self, message_obj: Any, text: str | None = None, file_path: str | None = None, with_spoiler: bool = False, *, parse_mode: str | None = None, **kwargs): ...

def get_client(account: int | None = None) -> AccountClient: ...

class NotificationCenterDelegate(Incomplete):
    def __init__(self) -> None: ...
    def didReceivedNotification(self, id: int, account: int, args: None): ...
