from _typeshed import Incomplete
from android.app import Activity
from android.graphics.drawable import Drawable
from dataclasses import dataclass, field
from enum import Enum
from java.io import File
from org.telegram.messenger import MessageObject
from org.telegram.ui.ActionBar import BaseFragment
from typing import Callable

def get_plugins_dir() -> str: ...
def get_cache_dir() -> str: ...
def get_files_dir() -> str: ...
def get_images_dir() -> str: ...
def get_videos_dir() -> str: ...
def get_audios_dir() -> str: ...
def get_documents_dir() -> str: ...
def read_file(file_path: str) -> str | None: ...
def read_file_bytes(file_path: str) -> bytes | None: ...
def write_file(file_path: str, content: str): ...
def write_file_bytes(file_path: str, content: bytes): ...
def delete_file(file_path: str) -> bool: ...
def ensure_dir_exists(dir_path: str): ...
def list_dir(path: str, recursive: bool = False, include_files: bool = True, include_dirs: bool = False, extensions: list[str] | None = None) -> list[str]: ...

class staticproperty:
    fget: Incomplete
    def __init__(self, fget) -> None: ...
    def __get__(self, obj, owner): ...

class FilesController:
    @staticproperty
    @staticmethod
    def DIRECT_FILE_ICONS() -> bool: ...
    @staticproperty
    @staticmethod
    def SUPPORT_ICONS() -> bool: ...
    class Place(Enum):
        UNKNOWN = 1
        ChatActivity = 2
        FilteredSearchView = 3
        SharedMediaLayout = 4
        SearchDownloadsContainer = 5
        ChannelAdminLogActivity = 6
    @dataclass
    class FileInfo:
        ext: str
        on_click: Callable[[FilesController.OnClickArgs], None] = field(compare=False, repr=False)
        whitelist_places: list['FilesController.Place'] = field(default_factory=list, kw_only=True)
        blacklist_places: list['FilesController.Place'] = field(default_factory=list, kw_only=True)
        get_icon: Callable[[], Drawable] | None = field(default=None, compare=False, repr=False, kw_only=True)
        def __post_init__(self) -> None: ...
    @dataclass
    class OnClickArgs:
        place: FilesController.Place
        file: File = field(compare=False, repr=False)
        file_name: str
        message: MessageObject = field(compare=False, repr=False)
        activity: Activity = field(compare=False, repr=False)
        parent_fragment: BaseFragment | None = field(default=None, compare=False, repr=False)
    class ExtensionAlreadyRegistered(Exception):
        def __init__(self, ext: str) -> None: ...
    class ExtensionNotRegistered(Exception):
        def __init__(self, ext: str) -> None: ...
    class SecretInvalid(Exception):
        def __init__(self, ext: str, secret: str) -> None: ...
    @classmethod
    def register(cls, file_info: FileInfo) -> str: ...
    @classmethod
    def unregister(cls, ext: str, secret: str): ...
