package vpn.proxy

import android.util.Log
import org.json.JSONObject
import java.util.Base64

/**
 * Thin wrapper around libxray (gomobile AAR).
 *
 * libXray API (generated by gomobile):
 *   libXray.LibXray.runXrayFromJSON(base64Request: String): String   — base64-encoded JSON response
 *   libXray.LibXray.stopXray(): String
 *   libXray.LibXray.getXrayState(): Boolean
 *
 * Start sequence: XrayProxy.start(configJson) → local SOCKS5 on 127.0.0.1:[socksPort] is available.
 * Stop sequence:  XrayProxy.stop().
 *
 * The proxy config is provided exclusively by the backend (POST /auth/register).
 * There is no hardcoded fallback — callers must supply a valid JSON config.
 */
object XrayProxy {

    private const val TAG = "XrayProxy"

    const val SOCKS_PORT = 17808
    val socksPort: Int = SOCKS_PORT
    val socksHost: String = "127.0.0.1"

    var lastError: String? = null
        private set

    fun isRunning(): Boolean = try {
        libXray.LibXray.getXrayState()
    } catch (e: Throwable) {
        Log.e(TAG, "getXrayState failed", e)
        false
    }

    fun start(configJson: String): Boolean {
        if (isRunning()) {
            Log.d(TAG, "Already running")
            return true
        }
        return try {
            val request = buildRunRequest(configJson)
            val responseBase64 = libXray.LibXray.runXrayFromJSON(request)
            val response = decodeResponse(responseBase64)
            if (response.isSuccess) {
                lastError = null
                Log.d(TAG, "Started on $socksHost:$socksPort")
                true
            } else {
                lastError = response.error
                Log.e(TAG, "Start failed: ${response.error}")
                false
            }
        } catch (e: Throwable) {
            lastError = "${e.javaClass.simpleName}: ${e.message}"
            Log.e(TAG, "Start exception", e)
            false
        }
    }

    fun stop() {
        try {
            libXray.LibXray.stopXray()
            Log.d(TAG, "Stopped")
        } catch (e: Throwable) {
            Log.e(TAG, "Stop exception", e)
        }
    }

    // ---- private helpers ----

    private fun buildRunRequest(configJson: String): String {
        val requestJson = JSONObject().apply {
            put("datDir", "")          // no geo dat files needed for basic VLESS
            put("mphCachePath", "")
            put("configJSON", configJson)
        }.toString()
        return Base64.getEncoder().encodeToString(requestJson.toByteArray())
    }

    private data class LibResponse(val isSuccess: Boolean, val error: String?)

    private fun decodeResponse(base64: String): LibResponse {
        return try {
            val json = String(Base64.getDecoder().decode(base64))
            val obj = JSONObject(json)
            val error = if (obj.has("error")) obj.optString("error").takeIf { it.isNotEmpty() } else null
            LibResponse(isSuccess = error == null, error = error)
        } catch (e: Throwable) {
            LibResponse(isSuccess = false, error = "Response parse error: ${e.message}")
        }
    }
}
