package vpn.proxy

import android.util.Log
import org.json.JSONObject
import java.util.Base64

/**
 * Thin wrapper around libxray (gomobile AAR).
 *
 * libXray API (generated by gomobile):
 *   libXray.LibXray.runXrayFromJSON(base64Request: String): String   — base64-encoded JSON response
 *   libXray.LibXray.stopXray(): String
 *   libXray.LibXray.getXrayState(): Boolean
 *
 * Start sequence: XrayProxy.start(configJson) → local SOCKS5 on 127.0.0.1:[socksPort] is available.
 * Stop sequence:  XrayProxy.stop().
 *
 * The proxy config is provided exclusively by the backend (POST /auth/register).
 * There is no hardcoded fallback — callers must supply a valid JSON config.
 */
object XrayProxy {

    private const val TAG = "XrayProxy"

    const val SOCKS_PORT = 17808
    val socksPort: Int = SOCKS_PORT
    val socksHost: String = "127.0.0.2"

    var lastError: String? = null
        private set

    var proxyLogger: ((String) -> Unit)? = null

    private fun logD(msg: String) {
        Log.d(TAG, msg)
        proxyLogger?.invoke("D/$TAG: $msg")
    }
    private fun logE(msg: String, t: Throwable? = null) {
        if (t != null) Log.e(TAG, msg, t) else Log.e(TAG, msg)
        proxyLogger?.invoke("E/$TAG: $msg" + (if (t != null) " - ${t.message}" else ""))
    }

    fun isRunning(): Boolean = try {
        libXray.LibXray.getXrayState()
    } catch (e: Throwable) {
        logE("getXrayState failed", e)
        false
    }

    /**
     * Real liveness check: [isRunning] only reflects libxray's internal
     * "did I start" flag, which stays true even if the Go runtime wedged or
     * the SOCKS5 listener stopped accepting connections. This actually
     * connects to the local SOCKS5 port to verify something is listening.
     */
    fun isHealthy(timeoutMs: Int = 300): Boolean {
        if (!isRunning()) return false
        return try {
            java.net.Socket().use { socket ->
                socket.connect(java.net.InetSocketAddress(socksHost, socksPort), timeoutMs)
                true
            }
        } catch (e: Exception) {
            logE("Health check failed: local SOCKS5 port not accepting connections", e)
            false
        }
    }

    /** Last result of [isHealthy], refreshed by the watchdog. See [isHealthyCached]. */
    @Volatile
    private var lastHealthy: Boolean = false

    /**
     * Non-blocking answer for callers on the main thread.
     *
     * [isHealthy] opens a real socket, so calling it from a UI callback — which is what the
     * connection-state observer used to do — stalls the frame for up to [timeoutMs] every
     * time the connection state flickers. Those callers read this cached value instead, and
     * the watchdog keeps it fresh from its own thread.
     */
    fun isHealthyCached(): Boolean = isRunning() && lastHealthy

    /** Runs the real check and stores the result. Must not be called from the main thread. */
    fun refreshHealth(timeoutMs: Int = 300): Boolean {
        val healthy = isHealthy(timeoutMs)
        lastHealthy = healthy
        return healthy
    }

    fun start(configJson: String): Boolean {
        if (isRunning()) {
            logD("Already running")
            return true
        }
        return try {
            val request = buildRunRequest(configJson)
            val responseBase64 = libXray.LibXray.runXrayFromJSON(request)
            val response = decodeResponse(responseBase64)
            if (response.isSuccess) {
                lastError = null
                logD("Started on $socksHost:$socksPort")
                startLogcatReader()
                true
            } else {
                lastError = response.error
                logE("Start failed: ${response.error}")
                false
            }
        } catch (e: Throwable) {
            lastError = "${e.javaClass.simpleName}: ${e.message}"
            logE("Start exception", e)
            false
        }
    }

    fun stop() {
        try {
            stopLogcatReader()
            libXray.LibXray.stopXray()
            logD("Stopped")
        } catch (e: Throwable) {
            logE("Stop exception", e)
        }
    }

    // ---- private helpers ----

    private fun buildRunRequest(configJson: String): String {
        var finalConfigJson = configJson.replace("\"127.0.0.1\"", "\"127.0.0.2\"")
        try {
            val configObj = JSONObject(finalConfigJson)
            if (!configObj.has("log")) {
                val logObj = JSONObject()
                logObj.put("loglevel", "debug")
                configObj.put("log", logObj)
                finalConfigJson = configObj.toString()
            }
        } catch (e: Exception) {
            logE("Failed to inject debug log level", e)
        }

        val requestJson = JSONObject().apply {
            put("datDir", "")          // no geo dat files needed for basic VLESS
            put("mphCachePath", "")
            put("configJSON", finalConfigJson)
        }.toString()
        return Base64.getEncoder().encodeToString(requestJson.toByteArray())
    }

    private var logcatThread: Thread? = null
    @Volatile private var isLogcatRunning = false

    private fun startLogcatReader() {
        if (isLogcatRunning) return
        isLogcatRunning = true
        logcatThread = kotlin.concurrent.thread(start = true) {
            try {
                val process = Runtime.getRuntime().exec("logcat -v time GoLog:D libxray:D XrayProxy:D VpnSDK:D *:S")
                val reader = java.io.BufferedReader(java.io.InputStreamReader(process.inputStream))
                var line: String? = null
                while (isLogcatRunning && reader.readLine().also { line = it } != null) {
                    val l = line ?: continue
                    if (l.contains("GoLog") || l.contains("libxray")) {
                        val msgIndex = l.indexOf("GoLog")
                        val cleanMsg = if (msgIndex != -1) l.substring(msgIndex) else l
                        proxyLogger?.invoke(cleanMsg)
                    }
                }
            } catch (e: Exception) {
                // Ignore
            }
        }
    }

    private fun stopLogcatReader() {
        isLogcatRunning = false
        logcatThread?.interrupt()
        logcatThread = null
    }

    private data class LibResponse(val isSuccess: Boolean, val error: String?)

    private fun decodeResponse(base64: String): LibResponse {
        return try {
            val json = String(Base64.getDecoder().decode(base64))
            val obj = JSONObject(json)
            val error = if (obj.has("error")) obj.optString("error").takeIf { it.isNotEmpty() } else null
            LibResponse(isSuccess = error == null, error = error)
        } catch (e: Throwable) {
            LibResponse(isSuccess = false, error = "Response parse error: ${e.message}")
        }
    }
}
