package org.telegram.messenger.plugins;

import android.os.Build;

import com.android.dx.Code;
import com.android.dx.DexMaker;
import com.android.dx.FieldId;
import com.android.dx.Local;
import com.android.dx.MethodId;
import com.android.dx.TypeId;

import org.telegram.messenger.ApplicationLoader;
import org.telegram.messenger.Utilities;

import java.io.File;
import java.io.FileOutputStream;
import java.lang.reflect.Constructor;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Random;

/**
 * PrimeGram: subclassing an arbitrary Java class from Python, at run time.
 *
 * <p>Chaquopy can implement a Java <em>interface</em> from Python ({@code java.dynamic_proxy}) -
 * that is real proxying, done by the JVM/ART itself, and needs nothing extra. It cannot extend a
 * Java <em>class</em>: there is no bytecode for that class until somebody generates it, and Chaquopy
 * does not carry a bytecode generator. This does - the same way exteraGram's own plugin SDK does,
 * decompiled and studied to confirm it was possible here at all before writing a line of this: a DEX
 * class is built in memory with <a href="https://github.com/linkedin/dexmaker">dexmaker</a> (an
 * AOSP-derived, Apache-licensed library - {@code com.android.dx}, the exact package exteraGram's own
 * generator calls into), loaded with {@link dalvik.system.InMemoryDexClassLoader}, and every
 * overridden method forwards to a single {@link Utilities.Callback3Return} that Python supplies.
 *
 * <p>What did not come along: exteraGram's version also lets a pre-construction hook rewrite the
 * arguments before {@code super(...)} runs, generates plain MVEL-expression method bodies as a
 * separate faster path, and can declare new fields with generated accessors. None of that is here -
 * a Python handler already covers what those exist to cover, just through the interpreter instead of
 * generated bytecode, and every extra generated-code path is another way this can be generated wrong
 * in a way that only shows up on a device. What is here: extending a class, implementing interfaces,
 * overriding named methods to call into Python, and a trampoline per overridden method so Python can
 * still call the original.
 *
 * <p>DexMaker's own generics fight the compiler in exactly the same spots the decompiled original
 * shows signs of working around (JADX renders several of its locals as raw {@code ??} where type
 * inference gave up) - this uses raw types throughout for the same reason, rather than fighting it.
 */
@SuppressWarnings({"unchecked", "rawtypes"})
public final class PrimeClassProxy {

    private static final String HANDLER_FIELD = "prime$handler";
    /** Public, per-instance, untyped: where the matching Python object lives. Set from Python the
     *  moment the constructor hook fires, read from Python on every call after - a real field, so
     *  finding it again does not depend on whether Chaquopy hands back the same wrapper object for
     *  the same Java instance twice, which nothing here relies on. */
    public static final String PEER_FIELD = "prime$peer";
    private static final String SUPER_PREFIX = "prime$super$";
    private static final String GENERATED_PACKAGE = "org.telegram.messenger.plugins.generated.";

    private static volatile ClassLoader sharedGeneratedClassLoader;
    private static final Object generatedClassLoaderLock = new Object();

    private PrimeClassProxy() {
    }

    /** Boxing/unboxing helpers the generated bytecode calls into - it only ever moves {@code Object}
     *  locals around, so a primitive value has to cross that boundary through here. */
    public static final class TypeHelper {
        private TypeHelper() {
        }

        public static Object box(byte v) { return v; }
        public static Object box(char v) { return v; }
        public static Object box(double v) { return v; }
        public static Object box(float v) { return v; }
        public static Object box(int v) { return v; }
        public static Object box(long v) { return v; }
        public static Object box(short v) { return v; }
        public static Object box(boolean v) { return v; }
        public static Object box(Object v) { return v; }

        public static boolean unboxBoolean(Object o) { return o instanceof Boolean && (Boolean) o; }
        public static byte unboxByte(Object o) { return o instanceof Number ? ((Number) o).byteValue() : 0; }
        public static char unboxChar(Object o) { return o instanceof Character ? (Character) o : 0; }
        public static double unboxDouble(Object o) { return o instanceof Number ? ((Number) o).doubleValue() : 0; }
        public static float unboxFloat(Object o) { return o instanceof Number ? ((Number) o).floatValue() : 0; }
        public static int unboxInt(Object o) { return o instanceof Number ? ((Number) o).intValue() : 0; }
        public static long unboxLong(Object o) { return o instanceof Number ? ((Number) o).longValue() : 0; }
        public static short unboxShort(Object o) { return o instanceof Number ? ((Number) o).shortValue() : 0; }
    }

    /**
     * Builds and loads a subclass of {@code superClass}.
     *
     * <p>Every overload of every name in {@code methodNames} that {@code superClass} (or an
     * ancestor) declares as public or protected, non-static and non-final gets overridden: the
     * override calls {@code handler.run(instance, "name:param.Class.Name:...", boxedArgs)} and
     * returns whatever comes back, unboxed to the real return type. A {@code prime$super$name}
     * method is generated alongside it that calls the original implementation directly, for a
     * handler that wants to call it - reflection cannot do that once the method is overridden.
     *
     * <p>Every constructor {@code superClass} declares (that is not private) is generated too,
     * forwarding its arguments to {@code super(...)} unchanged and then calling {@code
     * handler.run(instance, "<init>:...", boxedArgs)} once construction is complete, return value
     * discarded - a place for Python to finish setting the new instance up, not a way to change
     * how it gets built.
     *
     * <p>One handler serves every instance the returned class produces; the signature string is
     * how a call tells them apart.
     */
    public static Class<?> createProxyClass(Class<?> superClass, List<Class<?>> interfaces,
                                             List<String> methodNames,
                                             Utilities.Callback3Return<Object, String, Object[], Object> handler)
            throws ReflectiveOperationException {
        final DexMaker dexMaker = new DexMaker();

        String simpleName = superClass.getSimpleName();
        if (simpleName.isEmpty()) {
            simpleName = "Anon";
        }
        final String className = GENERATED_PACKAGE + simpleName + "_"
                + Math.abs(superClass.getName().hashCode()) + "_" + Math.abs(new Random().nextInt());
        final TypeId generated = TypeId.get("L" + className.replace('.', '/') + ";");
        final TypeId superType = TypeId.get(superClass);
        final FieldId handlerField = generated.getField(TypeId.get(Utilities.Callback3Return.class), HANDLER_FIELD);

        final List<TypeId> interfaceTypes = new ArrayList<>();
        if (interfaces != null) {
            for (Class<?> iface : interfaces) {
                if (iface == null) {
                    continue;
                }
                if (!iface.isInterface()) {
                    throw new IllegalArgumentException("не интерфейс: " + iface.getName());
                }
                interfaceTypes.add(TypeId.get(iface));
            }
        }

        dexMaker.declare(generated, className + ".java", Modifier.PUBLIC, superType,
                interfaceTypes.toArray(new TypeId[0]));
        dexMaker.declare(handlerField, Modifier.PUBLIC | Modifier.STATIC, null);
        dexMaker.declare(generated.getField(TypeId.OBJECT, PEER_FIELD), Modifier.PUBLIC, null);

        for (Constructor<?> constructor : superClass.getDeclaredConstructors()) {
            if (!Modifier.isPrivate(constructor.getModifiers())) {
                generateConstructor(dexMaker, generated, superType, constructor, handlerField);
            }
        }

        if (methodNames != null && !methodNames.isEmpty()) {
            final Map<String, Method> overridable = collectOverridable(superClass);
            for (String name : methodNames) {
                for (Method method : overridable.values()) {
                    if (method.getName().equals(name)) {
                        generateSuperTrampoline(dexMaker, generated, method);
                        generateHandlerMethod(dexMaker, generated, method, handlerField);
                    }
                }
            }
        }

        final byte[] dex = dexMaker.generate();
        final Class<?> loaded;
        synchronized (generatedClassLoaderLock) {
            final ClassLoader parent = sharedGeneratedClassLoader != null
                    ? sharedGeneratedClassLoader : ApplicationLoader.applicationContext.getClassLoader();
            final ClassLoader classLoader = loadDex(dex, parent, className);
            loaded = classLoader.loadClass(className);
            sharedGeneratedClassLoader = classLoader;
        }
        final Field field = loaded.getDeclaredField(HANDLER_FIELD);
        field.setAccessible(true);
        field.set(null, handler);
        return loaded;
    }

    private static ClassLoader loadDex(byte[] dex, ClassLoader parent, String className) throws ReflectiveOperationException {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            return new dalvik.system.InMemoryDexClassLoader(ByteBuffer.wrap(dex), parent);
        }
        // Below API 26 there is no in-memory loader - the bytes have to sit in a file first, the
        // same way every dex loader worked before InMemoryDexClassLoader existed.
        final File dir = new File(ApplicationLoader.applicationContext.getCodeCacheDir(), "prime_class_proxy");
        //noinspection ResultOfMethodCallIgnored
        dir.mkdirs();
        final File dexFile = new File(dir, className.hashCode() + "_" + System.nanoTime() + ".dex");
        try (FileOutputStream out = new FileOutputStream(dexFile)) {
            out.write(dex);
        } catch (Exception e) {
            throw new ReflectiveOperationException(e);
        }
        return new dalvik.system.DexClassLoader(dexFile.getAbsolutePath(), dir.getAbsolutePath(), null, parent);
    }

    private static String signature(String name, Class<?>[] params) {
        final StringBuilder sb = new StringBuilder(name);
        if (params != null) {
            for (Class<?> p : params) {
                sb.append(':').append(p.getName());
            }
        }
        return sb.toString();
    }

    private static String capitalize(Class<?> primitive) {
        final String name = primitive.getName();
        return Character.toUpperCase(name.charAt(0)) + name.substring(1);
    }

    private static Map<String, Method> collectOverridable(Class<?> cls) {
        final LinkedHashMap<String, Method> result = new LinkedHashMap<>();
        for (Class<?> c = cls; c != null && c != Object.class; c = c.getSuperclass()) {
            for (Method m : c.getDeclaredMethods()) {
                final int mod = m.getModifiers();
                if (!Modifier.isStatic(mod) && !Modifier.isFinal(mod)
                        && (Modifier.isPublic(mod) || Modifier.isProtected(mod))) {
                    result.putIfAbsent(signature(m.getName(), m.getParameterTypes()), m);
                }
            }
        }
        return result;
    }

    private static TypeId[] typeIdsOf(Class<?>[] classes) {
        final TypeId[] result = new TypeId[classes.length];
        for (int i = 0; i < classes.length; i++) {
            result[i] = TypeId.get(classes[i]);
        }
        return result;
    }

    /** {@code super(...)}, forwarded unchanged, then a post-construction call to the handler. */
    private static void generateConstructor(DexMaker dexMaker, TypeId generated, TypeId superType,
                                              Constructor<?> constructor, FieldId handlerField) {
        final Class<?>[] paramTypes = constructor.getParameterTypes();
        final TypeId[] paramTypeIds = typeIdsOf(paramTypes);

        final Code code = dexMaker.declare(generated.getConstructor(paramTypeIds), Modifier.PUBLIC);
        final TypeId object = TypeId.OBJECT;
        final TypeId callbackType = TypeId.get(Utilities.Callback3Return.class);
        final MethodId run = callbackType.getMethod(object, "run", object, object, object);

        final Local self = code.getThis(generated);
        final Local[] params = new Local[paramTypes.length];
        for (int i = 0; i < paramTypes.length; i++) {
            params[i] = code.getParameter(i, paramTypeIds[i]);
        }
        code.invokeDirect(superType.getConstructor(paramTypeIds), null, self, params);

        final Local handler = code.newLocal(callbackType);
        code.sget(handlerField, handler);
        final Local selfBoxed = code.newLocal(object);
        code.cast(selfBoxed, self);
        final Local sig = code.newLocal(TypeId.STRING);
        code.loadConstant(sig, signature("<init>", paramTypes));
        final Local args = boxArgs(code, params, paramTypes);
        final Local unused = code.newLocal(object);
        code.invokeInterface(run, unused, handler, selfBoxed, sig, args);
        code.returnVoid();
    }

    /** {@code prime$super$name(...)}: calls the original implementation, nothing else. Lets a
     *  handler that just overrode {@code name} still reach what it would otherwise have done. */
    private static void generateSuperTrampoline(DexMaker dexMaker, TypeId generated, Method method) {
        final Class<?>[] paramTypes = method.getParameterTypes();
        final TypeId[] paramTypeIds = typeIdsOf(paramTypes);
        final TypeId returnType = TypeId.get(method.getReturnType());

        final Code code = dexMaker.declare(
                generated.getMethod(returnType, SUPER_PREFIX + method.getName(), paramTypeIds), Modifier.PUBLIC);
        final Local self = code.getThis(generated);
        final Local[] params = new Local[paramTypes.length];
        for (int i = 0; i < paramTypes.length; i++) {
            params[i] = code.getParameter(i, paramTypeIds[i]);
        }
        final boolean isVoid = returnType.equals(TypeId.VOID);
        final Local result = isVoid ? null : code.newLocal(returnType);
        code.invokeSuper(TypeId.get(method.getDeclaringClass()).getMethod(returnType, method.getName(), paramTypeIds),
                result, self, params);
        if (isVoid) {
            code.returnVoid();
        } else {
            code.returnValue(result);
        }
    }

    /** {@code name(...)}: boxes every argument, calls the handler, unboxes what comes back. */
    private static void generateHandlerMethod(DexMaker dexMaker, TypeId generated, Method method, FieldId handlerField) {
        final Class<?>[] paramTypes = method.getParameterTypes();
        final TypeId[] paramTypeIds = typeIdsOf(paramTypes);
        final Class<?> returnClass = method.getReturnType();
        final TypeId returnType = TypeId.get(returnClass);
        final TypeId object = TypeId.OBJECT;
        final TypeId callbackType = TypeId.get(Utilities.Callback3Return.class);
        final MethodId run = callbackType.getMethod(object, "run", object, object, object);

        final Code code = dexMaker.declare(generated.getMethod(returnType, method.getName(), paramTypeIds), Modifier.PUBLIC);
        final Local self = code.getThis(generated);
        final Local[] params = new Local[paramTypes.length];
        for (int i = 0; i < paramTypes.length; i++) {
            params[i] = code.getParameter(i, paramTypeIds[i]);
        }

        final Local handler = code.newLocal(callbackType);
        code.sget(handlerField, handler);
        final Local selfBoxed = code.newLocal(object);
        code.cast(selfBoxed, self);
        final Local sig = code.newLocal(TypeId.STRING);
        code.loadConstant(sig, signature(method.getName(), paramTypes));
        final Local args = boxArgs(code, params, paramTypes);
        final Local resultBoxed = code.newLocal(object);
        code.invokeInterface(run, resultBoxed, handler, selfBoxed, sig, args);

        if (returnType.equals(TypeId.VOID)) {
            code.returnVoid();
            return;
        }
        if (returnClass.isPrimitive()) {
            final Local result = code.newLocal(returnType);
            code.invokeStatic(TypeId.get(TypeHelper.class).getMethod(returnType, "unbox" + capitalize(returnClass), object),
                    result, resultBoxed);
            code.returnValue(result);
        } else {
            final Local result = code.newLocal(returnType);
            code.cast(result, resultBoxed);
            code.returnValue(result);
        }
    }

    /** Builds an {@code Object[]} of {@code params}, boxing whichever ones are primitive. */
    private static Local boxArgs(Code code, Local[] params, Class<?>[] paramTypes) {
        final TypeId object = TypeId.OBJECT;
        final TypeId objectArray = TypeId.get(Object[].class);
        final Local length = code.newLocal(TypeId.INT);
        code.loadConstant(length, params.length);
        final Local args = code.newLocal(objectArray);
        code.newArray(args, length);
        final Local index = code.newLocal(TypeId.INT);
        for (int i = 0; i < params.length; i++) {
            final Local boxed = code.newLocal(object);
            final TypeId paramType = TypeId.get(paramTypes[i]);
            code.invokeStatic(TypeId.get(TypeHelper.class).getMethod(object, "box",
                    paramTypes[i].isPrimitive() ? paramType : object), boxed, params[i]);
            code.loadConstant(index, i);
            code.aput(args, index, boxed);
        }
        return args;
    }
}
